name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # find more here https://github.com/cypress-io/github-action/releases
      - name: Cypress run
        uses: cypress-io/github-action@v2.11.7 
        with:
          start: npm test
          wait-on: http://localhost:8080