name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm i


      - name: Cypress run
        uses: cypress-io/github-action@v2.9.3
        with:
          start: npm test
          wait-on: http://localhost:8080